include(${CMAKE_CURRENT_LIST_DIR}/stm32f4_base.cmake)

set(CAFFEINE_MCU_MACRO "STM32F407xx" CACHE STRING "Vendor SDK MCU Macro")
set(CAFFEINE_LINKER_SCRIPT "STM32F407VGTX_FLASH.ld" CACHE STRING "Linker script")
