set(CAFFEINE_MCU_CORE "cortex-m4" CACHE STRING "MCU Core architecture")
set(CAFFEINE_MCU_COMPILE_OPTIONS "-mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16" CACHE STRING "Hardware-specific compiler flags")

# Default peripheral sets
set(CFN_HAL_ADC "ON" CACHE STRING "Enable ADC HAL peripheral")
set(CFN_HAL_CLOCK "ON" CACHE STRING "Enable Clock HAL peripheral")
set(CFN_HAL_DMA "ON" CACHE STRING "Enable DMA HAL peripheral")
set(CFN_HAL_GPIO "ON" CACHE STRING "Enable GPIO HAL peripheral")
set(CFN_HAL_I2C "ON" CACHE STRING "Enable I2C HAL peripheral")
set(CFN_HAL_I2S "ON" CACHE STRING "Enable I2S HAL peripheral")
set(CFN_HAL_IRQ "ON" CACHE STRING "Enable IRQ HAL peripheral")
set(CFN_HAL_NVM "ON" CACHE STRING "Enable NVM HAL peripheral")
set(CFN_HAL_PWM "ON" CACHE STRING "Enable PWM HAL peripheral")
set(CFN_HAL_RTC "ON" CACHE STRING "Enable RTC HAL peripheral")
set(CFN_HAL_SDIO "ON" CACHE STRING "Enable SDIO HAL peripheral")
set(CFN_HAL_SPI "ON" CACHE STRING "Enable SPI HAL peripheral")
set(CFN_HAL_TIMER "ON" CACHE STRING "Enable TIMER HAL peripheral")
set(CFN_HAL_UART "ON" CACHE STRING "Enable UART HAL peripheral")
set(CFN_HAL_WDT "ON" CACHE STRING "Enable WDT HAL peripheral")
set(CFN_HAL_CAN "ON" CACHE STRING "Enable CAN HAL peripheral")
set(CFN_HAL_ETH "ON" CACHE STRING "Enable ETH HAL peripheral")
set(CFN_HAL_USB "ON" CACHE STRING "Enable USB HAL peripheral")