include(${CMAKE_CURRENT_LIST_DIR}/stm32f4_base.cmake)

set(CAFFEINE_MCU_MACRO "STM32F417xx" CACHE STRING "Vendor SDK MCU Macro")
set(CAFFEINE_LINKER_SCRIPT "STM32F417VGTX_FLASH.ld" CACHE STRING "Linker script")

set(CFN_HAL_CRYPTO "ON" CACHE STRING "Enable CRYPTO HAL peripheral")
set(CFN_HAL_HASH "ON" CACHE STRING "Enable HASH HAL peripheral")
set(CFN_HAL_RNG "ON" CACHE STRING "Enable RNG HAL peripheral")
