set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CAFFEINE_TOOLCHAIN_PREFIX "aarch64-linux-gnu-" CACHE STRING "Compiler toolchain prefix")

set(CMAKE_C_COMPILER ${CAFFEINE_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${CAFFEINE_TOOLCHAIN_PREFIX}g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
