name: Framework CI

on:
  workflow_call:
    inputs:
      submodules:
        description: 'Submodule checkout strategy (recursive, true, false)'
        required: false
        default: 'recursive'
        type: string

jobs:
  discover:
    name: Discovery
    runs-on: ubuntu-24.04
    outputs:
      universe: ${{ steps.set-matrix.outputs.universe }}
      hardware: ${{ steps.set-matrix.outputs.hardware }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.submodules }}
      - id: set-matrix
        name: Generate Preset Matrix
        run: |
          RAW_MATRIX=$(python3 ./caffeine-build/scripts/ci.py list)
          echo "universe=$(echo $RAW_MATRIX | jq -c .universe)" >> $GITHUB_OUTPUT
          echo "hardware=$(echo $RAW_MATRIX | jq -c .hardware)" >> $GITHUB_OUTPUT

  lint-format:
    name: Format
    needs: discover
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        preset: ${{ fromJson(needs.discover.outputs.universe) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.submodules }}
      - name: Check Formatting
        run: python3 ./caffeine-build/scripts/ci.py format ${{ matrix.preset.name }}

  documentation:
    name: Docs
    needs: [discover, lint-format]
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        preset: ${{ fromJson(needs.discover.outputs.universe) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.submodules }}
      - name: Build Documentation
        run: python3 ./caffeine-build/scripts/ci.py doc ${{ matrix.preset.name }}

  static-analysis:
    name: Analysis
    needs: [discover, documentation]
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        preset: ${{ fromJson(needs.discover.outputs.universe) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.submodules }}
      - name: Run Static Analysis
        run: python3 ./caffeine-build/scripts/ci.py analyze ${{ matrix.preset.name }}

  build-and-test:
    name: Build & Test
    needs: [discover, static-analysis]
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        preset: ${{ fromJson(needs.discover.outputs.hardware) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.submodules }}
      - name: Build All Targets
        run: python3 ./caffeine-build/scripts/ci.py build ${{ matrix.preset.name }}
      - name: Run Unit Tests
        if: ${{ matrix.preset.tests }}
        run: python3 ./caffeine-build/scripts/ci.py test ${{ matrix.preset.name }}
